name: Hello World with Secrets

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  hello:
    runs-on: ubuntu-latest

    env:
      # 👇 Map GitHub secret DATABASE_PASSWORD to Terraform variable db_password
      TF_VAR_db_password: ${{ secrets.DATABASE_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Say hello
        run: echo "👋 Hello World from GitHub Actions!"

      - name: Show DB Password (safe test)
        run: echo "Terraform will see db_password is set ✅"